In [19]:
import pandas as pd
import numpy as np
from FCI_functions.FCI_functions import calculate_pre_score, calculate_post_score, calculate_question_score_post, calculate_question_score_pre

In [20]:
df20 = pd.read_excel('rawdata/2020-21 WT1 Phys 111&112 ALL Data - Shared with Chelsea (20210329).xlsx').replace(["BLANK", "!!"], None)
is_111 = df20['Course'] == 111
df20_111 = df20[is_111]
is_112 = df20['Course'] == 112
df20_112 = df20[is_112]

pre_2020 = ['PRE Q1'] 
for i in range (24, 53):
    string = 'PRE Q' + str(i)
    pre_2020.append(string)
    
pre = []
for i in range (1,31):
    string = "PRE Q" + str(i)
    pre.append(string)

df20_112_pre = df20_112[pre_2020]

df20_112_pre.columns = pre

df20_112_pre.head()

,PRE Q1,PRE Q2,PRE Q3,PRE Q4,PRE Q5,PRE Q6,PRE Q7,PRE Q8,PRE Q9,PRE Q10,...,PRE Q21,PRE Q22,PRE Q23,PRE Q24,PRE Q25,PRE Q26,PRE Q27,PRE Q28,PRE Q29,PRE Q30
251,3.0,4.0,1.0,1.0,5.0,2.0,3.0,4.0,3.0,2.0,...,3.0,2.0,5.0,2.0,1.0,4.0,3.0,2.0,4.0,2.0
252,5.0,1.0,4.0,5.0,5.0,1.0,4.0,2.0,2.0,4.0,...,1.0,2.0,1.0,3.0,5.0,4.0,3.0,2.0,5.0,2.0
253,5.0,4.0,2.0,2.0,4.0,2.0,3.0,3.0,3.0,1.0,...,3.0,2.0,5.0,5.0,5.0,1.0,0.0,0.0,0.0,0.0
254,4.0,3.0,2.0,2.0,5.0,2.0,3.0,3.0,3.0,1.0,...,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0
255,3.0,2.0,4.0,4.0,5.0,2.0,4.0,4.0,3.0,3.0,...,2.0,3.0,2.0,2.0,4.0,1.0,2.0,2.0,4.0,2.0

In [22]:
is_f = df20_112['PRE Q13']== 1
df_f = df20_112[is_f]
df_pre_f = df20_112_pre.dropna(thresh=25, axis=0)
df_post_f = df_f[post].dropna(thresh=25, axis=0)

pre_f = df_pre_f.apply(calculate_pre_score_2020, axis=1).mean()
pre_f_error = df_pre_f.apply(calculate_pre_score_2020, axis=1).sem(axis=0)
post_f =df_post_f.apply(calculate_post_score, axis=1).mean()
post_f_error = df_post_f.apply(calculate_post_score, axis=1).sem(axis=0)
gain_f_error = np.sqrt(pre_f_error**2 + post_f_error**2)

In [23]:
def calculate_pre_score_2020(student):
    corr_ans = [3,1,3,5,2,2,2,2,5,1,4,2,4,4,1,1,2,2,5,4,5,2,2,1,3,5,3,5,2,3]
    pre = [] 
    for i in range (1, 31):
        string = "PRE Q" + str(i)
        pre.append(string)
    score = 0
    for i in range(1,31):
            if student[pre[i-1]]==corr_ans[i-1]:
                score+=1
            
    return (score)

In [24]:
def calculate_post_score_2020(student):
    corr_ans = [3,1,3,5,2,2,2,2,5,1,4,2,4,4,1,1,2,2,5,4,5,2,2,1,3,5,3,5,2,3]
    pre = [] 
    for i in range (1, 31):
        string = "POST Q" + str(i)
        pre.append(string)
    score = 0
    for i in range(1,31):
            if student[pre[i-1]]==corr_ans[i-1]:
                score+=1
            
    return (score)

In [54]:
def by_gender_by_year_2020(df, name):
    pre = []
    for i in range (1,31):
        string = "PRE Q" + str(i)
        pre.append(string)
    post = []
    for i in range (1,31):
        string = "POST Q" + str(i)
        post.append(string)

    pre_2020 = ['PRE Q1'] 
    for i in range (24, 53):
        string = 'PRE Q' + str(i)
        pre_2020.append(string)

    post_2020 = ['POST Q1'] 
    for i in range (24, 53):
        string = 'POST Q' + str(i)
        post_2020.append(string)

    df_pre = df[pre_2020]

    df_pre.columns = pre

    is_f = df['PRE Q12']== 1
    df_f = df[is_f]
    df_pre_f = df_f[pre_2020].dropna(thresh=1, axis=0)
    df_pre_f.columns = pre
    df_post_f = df_f[post].dropna(thresh=1, axis=0)

    pre_f = df_pre_f.apply(calculate_pre_score_2020, axis=1).mean()
    pre_f_error = df_pre_f.apply(calculate_pre_score_2020, axis=1).sem(axis=0)
    post_f =df_post_f.apply(calculate_post_score_2020, axis=1).mean()
    post_f_error = df_post_f.apply(calculate_post_score_2020, axis=1).sem(axis=0)
    gain_f_error = np.sqrt(pre_f_error**2 + post_f_error**2)

    is_m = df['PRE Q12']== 3
    df_m = df[is_m]
    df_pre_m = df_m[pre_2020].dropna(thresh=1, axis=0)
    df_pre_m.columns = pre
    df_post_m = df_m[post].dropna(thresh=1, axis=0)

    pre_m = df_pre_m.apply(calculate_pre_score_2020, axis=1).mean()
    pre_m_error = df_pre_m.apply(calculate_pre_score_2020, axis=1).sem(axis=0)
    post_m =df_post_m.apply(calculate_post_score_2020, axis=1).mean()
    post_m_error = df_post_m.apply(calculate_post_score_2020, axis=1).sem(axis=0)
    gain_m_error = np.sqrt(pre_m_error**2 + post_m_error**2)

    array = [name, pre_f, pre_f_error, post_f, post_f_error, post_f-pre_f, gain_f_error, pre_m, pre_m_error, post_m, post_m_error, post_m-pre_m, gain_m_error]
    return array

In [58]:
is_111 = df20['Course'] == 111
df20_111 = df20[is_111]
is_112 = df20['Course'] == 112
df20_112 = df20[is_112]


column_names=["YEAR", "Pre Score F", "Pre Score F Error", "Post Score F","Post Score F Error", "Gain F", "Gain Error", "Pre Score M", "Pre Score M Error", "Post Score M", "Post Score M Error", "Gain M", "Gain M Error"]
df = pd.DataFrame(columns=column_names)


df.loc[1] = by_gender_by_year_2020(df20_111, "2020 111")
df.loc[2] = by_gender_by_year_2020(df20_112, "2020 112")

df

,YEAR,Pre Score F,Pre Score F Error,Post Score F,Post Score F Error,Gain F,Gain Error,Pre Score M,Pre Score M Error,Post Score M,Post Score M Error,Gain M,Gain M Error
1,2020 112,6.115942,0.241246,6.087719,0.356009,-0.028223,0.430049,6.141935,0.148287,6.873874,0.295230,0.731938,0.330378
2,2020 112,6.024590,0.128946,6.502326,0.166647,0.477735,0.210709,6.198276,0.186589,6.753086,0.335884,0.554811,0.384231