In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from FCI_functions import calculate_post_score, calculate_pre_score, calculate_question_score_post, calculate_question_score_pre, calculate_pre_score_2020, calculate_post_score_2020, calculate_question_score_pre_2020 , calculate_question_score_post_2020, calculate_question_score_pre_2021, calculate_question_score_post_2021, calculate_question_score_post_2021_err

In [2]:
df16_111 = pd.read_excel('rawdata/2016-17 WT1 Phys 111 ALL Data - Shared with Chelsea.xlsx').replace(["BLANK", "!!", "MULT"], np.nan)
df16_112 = pd.read_excel('rawdata/2016-17 WT1 Phys 112 ALL Data - Shared with Chelsea.xlsx').replace(["BLANK", "!!", "MULT"], np.nan)
df14_111 = pd.read_excel('rawdata/2014-15 WT1 Phys 111 ALL Data - Shared with Chelsea (20210212).xlsx').replace(["BLANK", "!!", "MULT"], np.nan)
df14_112 = pd.read_excel('rawdata/2014-15 WT1 Phys 112 ALL Data - Shared with Chelsea (20210212).xlsx').replace(["BLANK", "!!", "MULT"], np.nan)
df15_111 = pd.read_excel('rawdata/2015-16 WT1 Phys 111 ALL Data - Shared with Chelsea.xlsx').replace(["BLANK", "!!", "MULT"], np.nan)
df15_112 = pd.read_excel('rawdata/2015-16 WT1 Phys 112 ALL Data - Shared with Chelsea.xlsx').replace(["BLANK", "!!", "MULT"], np.nan)
df17_111 = pd.read_excel('rawdata/2017-18 WT1 Phys 111 ALL Data - Shared with David (20190612).xlsx').replace(["BLANK", "!!", "MULT"], np.nan)
df17_112 = pd.read_excel('rawdata/2017-18 WT1 Phys 112 ALL Data - Shared with David (20190612).xlsx').replace(["BLANK", "!!", "MULT"], np.nan)
df18_111 = pd.read_excel('rawdata/2018-19 WT1 Phys 111 ALL Data - Shared with David (20190530).xlsx').replace(["BLANK", "!!", "MULT"], np.nan)
df18_112 = pd.read_excel('rawdata/2018-19 WT1 Phys 112 ALL Data - Shared with David (20190527).xlsx').replace(["BLANK", "!!", "MULT"], np.nan)#.drop(df18_112[df18_112['Secondary'] == L15].index)
df19_111 = pd.read_excel('rawdata/2019-20 WT1 Phys 111 ALL Data - Shared with Maya (20211222).xlsx').replace(["BLANK", "!!", "MULT"], np.nan)
df19_112 = pd.read_excel('rawdata/2019-20 WT1 Phys 112 ALL Data - Shared with Maya (20211222).xlsx').replace(["BLANK", "!!", "MULT"], np.nan)
df20 = pd.read_excel('rawdata/2020-21 WT1 Phys 111&112 ALL Data - Shared with Chelsea (20210329).xlsx').replace(["BLANK", "!!", "MULT"], np.nan)
is_111 = df20['Course'] == 111
df20_111 = df20[is_111]
is_112 = df20['Course'] == 112
df20_112 = df20[is_112]

df21_111 = pd.read_excel('2021raw_corrected.xlsx')

In [3]:
def calculate_scores(df):
    df_result = pd.DataFrame()
    df_result["PRE Q1"] = (df["PRE Q1"].value_counts())
    df_result["PRE Q2"] = (df["PRE Q2"].value_counts())
    df_result["PRE Q3"] = (df["PRE Q3"].value_counts())
    df_result["PRE Q4"] = (df["PRE Q4"].value_counts())
    df_result["PRE Q5"] = (df["PRE Q5"].value_counts())
    df_result["PRE Q6"] = (df["PRE Q6"].value_counts())
    df_result["PRE Q7"] = (df["PRE Q7"].value_counts())
    df_result["PRE Q8"] = (df["PRE Q8"].value_counts())
    df_result["PRE Q9"] = (df["PRE Q9"].value_counts())
    df_result["PRE Q10"] = (df["PRE Q10"].value_counts())
    df_result["PRE Q11"] = (df["PRE Q11"].value_counts())
    df_result["PRE Q12"] = (df["PRE Q12"].value_counts())
    df_result["PRE Q13"] = (df["PRE Q13"].value_counts())
    df_result["PRE Q14"] = (df["PRE Q14"].value_counts())
    df_result["PRE Q15"] = (df["PRE Q15"].value_counts())
    df_result["PRE Q16"] = (df["PRE Q16"].value_counts())
    df_result["PRE Q17"] = (df["PRE Q17"].value_counts())
    df_result["PRE Q18"] = (df["PRE Q18"].value_counts())
    df_result["PRE Q19"] = (df["PRE Q19"].value_counts())
    df_result["PRE Q20"] = (df["PRE Q20"].value_counts())
    df_result["PRE Q21"] = (df["PRE Q21"].value_counts())
    df_result["PRE Q22"] = (df["PRE Q22"].value_counts())
    df_result["PRE Q23"] = (df["PRE Q23"].value_counts())
    df_result["PRE Q24"] = (df["PRE Q24"].value_counts())
    df_result["PRE Q25"] = (df["PRE Q25"].value_counts())
    df_result["PRE Q26"] = (df["PRE Q26"].value_counts())
    df_result["PRE Q27"] = (df["PRE Q27"].value_counts())
    df_result["PRE Q28"] = (df["PRE Q28"].value_counts())
    df_result["PRE Q29"] = (df["PRE Q29"].value_counts())
    df_result["PRE Q30"] = (df["PRE Q30"].value_counts())

    return df_result

In [35]:
(calculate_scores(df14_111)["PRE Q30"].B+calculate_scores(df14_111)["PRE Q30"].D+calculate_scores(df14_111)["PRE Q30"].E)/calculate_scores(df14_111)["PRE Q30"].sum()

0.7114093959731543

In [21]:
def calculate_misconceptions(df):
    df_results = [0] * 32
    df_results[0] = (df["PRE Q1"].D + df["PRE Q1"].E)/df["PRE Q1"].sum()
    df_results[1] = (df["PRE Q2"].B + df["PRE Q2"].C)/df["PRE Q2"].sum()
    df_results[2] = (df["PRE Q3"].A)/df["PRE Q3"].sum()
    df_results[3] = (df["PRE Q4"].A)/df["PRE Q4"].sum()
    df_results[4] = (df["PRE Q5"].E)/df["PRE Q5"].sum()
    df_results[5] = (df["PRE Q5"].C+df["PRE Q5"].D)/df["PRE Q5"].sum()
    df_results[6] = (df["PRE Q6"].A)/df["PRE Q6"].sum()
    df_results[7] = (df["PRE Q6"].C+df["PRE Q6"].D+df["PRE Q6"].E)/df["PRE Q6"].sum()
    df_results[8] = (df["PRE Q7"].A)/df["PRE Q7"].sum()
    df_results[9] = (df["PRE Q7"].E)/df["PRE Q7"].sum()
    df_results[10] = (df["PRE Q8"].A)/df["PRE Q8"].sum()
    df_results[11] = (df["PRE Q9"].C)/df["PRE Q9"].sum()
    df_results[12] = (df["PRE Q9"].D)/df["PRE Q9"].sum()
    df_results[13] = (df["PRE Q10"].B + df["PRE Q10"].C)/df["PRE Q10"].sum()
    df_results[14] = (df["PRE Q11"].B + df["PRE Q11"].C)/df["PRE Q11"].sum()
    df_results[15] = (df["PRE Q13"].A+df["PRE Q13"].B+df["PRE Q13"].C)/df["PRE Q13"].sum()
    df_results[16] = (df["PRE Q13"].E)/df["PRE Q13"].sum()
    df_results[17] = (df["PRE Q14"].E)/df["PRE Q14"].sum()
    df_results[18] = (df["PRE Q15"].B)/df["PRE Q15"].sum()
    df_results[19] = (df["PRE Q16"].B)/df["PRE Q16"].sum()
    df_results[20] = (df["PRE Q17"].A)/df["PRE Q17"].sum()
    df_results[21] = (df["PRE Q18"].C+df["PRE Q18"].D+df["PRE Q18"].E)/df["PRE Q18"].sum()
    df_results[22] = (df["PRE Q19"].A)/df["PRE Q19"].sum()
    df_results[23] = (df["PRE Q20"].A+df["PRE Q20"].C)/df["PRE Q20"].sum()
    df_results[24] = (df["PRE Q25"].D)/df["PRE Q25"].sum()
    df_results[25] = (df["PRE Q25"].E)/df["PRE Q25"].sum()
    df_results[26] = (df["PRE Q26"].A+df["PRE Q26"].B)/df["PRE Q26"].sum()
    df_results[27] = (df["PRE Q27"].A)/df["PRE Q27"].sum()
    df_results[28] = (df["PRE Q28"].D)/df["PRE Q28"].sum()
    df_results[29] = (df["PRE Q29"].E)/df["PRE Q29"].sum()
    df_results[30] = (df["PRE Q29"].C+df["PRE Q29"].D)/df["PRE Q29"].sum()
    df_results[31] = (df["PRE Q30"].B+df["PRE Q30"].D+df["PRE Q30"].E)/df["PRE Q30"].sum()
    
    return df_results

In [22]:
column_names=["PRE Q1", "PRE Q2", "PRE Q3", "PRE Q4", "PRE Q5 32", "PRE Q5 22",
             "PRE Q6 31", "PRE Q6 19", "PRE Q7 31", "PRE Q7 19", "PRE Q8",
             "PRE Q9 66", "PRE Q9 9", "PRE Q10 21", "PRE Q11", "PRE Q13 77 22",
             "PRE Q13 69", "PRE Q14", "PRE Q15", "PRE Q16", "PRE Q17", "PRE Q18", 
             "PRE Q19", "PRE 20", "PRE Q25 76", "PRE Q25 24", "PRE Q26", "PRE Q27",
             "PRE Q28", "PRE Q29 28", "PRE Q29 air", "PRE Q30"]
df1 = pd.DataFrame(columns=column_names)

df1.loc["2014 111"] = calculate_misconceptions(calculate_scores(df14_111))
df1.loc["2014 112"] = calculate_misconceptions(calculate_scores(df14_112))
df1.loc["2015 111"] = calculate_misconceptions(calculate_scores(df15_111))
df1.loc["2015 112"] = calculate_misconceptions(calculate_scores(df15_112))
df1.loc["2016 111"] = calculate_misconceptions(calculate_scores(df16_111))
df1.loc["2016 112"] = calculate_misconceptions(calculate_scores(df16_112))
df1.loc["2017 111"] = calculate_misconceptions(calculate_scores(df17_111))
df1.loc["2017 112"] = calculate_misconceptions(calculate_scores(df17_112))
df1.loc["2018 111"] = calculate_misconceptions(calculate_scores(df18_111))
df1.loc["2018 112"] = calculate_misconceptions(calculate_scores(df18_112))
df1.loc["2019 111"] = calculate_misconceptions(calculate_scores(df19_111))
df1.loc["2019 112"] = calculate_misconceptions(calculate_scores(df19_112))
df1.loc["mean"] = df1.mean()
df1.to_excel("misconception_by_question_pre.xlsx")
df1

,PRE Q1,PRE Q2,PRE Q3,PRE Q4,PRE Q5 32,PRE Q5 22,PRE Q6 31,PRE Q6 19,PRE Q7 31,PRE Q7 19,...,PRE Q19,PRE 20,PRE Q25 76,PRE Q25 24,PRE Q26,PRE Q27,PRE Q28,PRE Q29 28,PRE Q29 air,PRE Q30
2014 111,0.111111,0.184211,0.111111,0.568627,0.143791,0.503268,0.150327,NaN,0.111111,0.065359,...,0.091503,0.307190,0.411765,0.137255,0.614379,0.209150,0.394737,0.026667,0.200000,0.711409
2014 112,0.286408,0.248780,0.247573,0.717073,0.199029,0.626214,0.300971,0.092233,0.223301,0.116505,...,0.179612,0.436893,0.543689,0.169903,0.830097,0.326829,0.612745,0.014634,0.263415,0.887255
2015 111,0.113208,0.238095,0.150943,0.712264,0.156398,0.540284,0.146226,0.066038,0.136792,0.070755,...,0.118483,0.341232,0.514286,0.123810,0.639810,0.213270,0.438095,0.009569,0.196172,0.750000
2015 112,0.171548,0.326360,0.229167,0.737500,0.229167,0.595833,0.292887,0.058577,0.166667,0.095833,...,0.184100,0.405858,0.516807,0.201681,0.715481,0.297071,0.472574,0.046414,0.265823,0.833333
2016 111,0.158491,0.231939,0.079245,0.619772,0.184906,0.479245,0.132075,0.037736,0.109434,0.037736,...,0.135135,0.381323,0.485714,0.126531,0.687243,0.231405,0.394191,0.012397,0.173554,0.659751
2016 112,0.253472,0.283217,0.207612,0.674740,0.216783,0.583916,0.298611,0.072917,0.204861,0.114583,...,0.167247,0.439024,0.501742,0.167247,0.725694,0.270833,0.512545,0.053381,0.316726,0.865942
2017 111,0.148936,0.192513,0.159574,0.547872,0.165775,0.465241,0.159574,NaN,0.122340,0.037234,...,0.117021,0.276596,0.486631,0.069519,0.569149,0.176471,0.358289,0.016043,0.171123,NaN
2017 112,0.256506,0.281955,0.251880,0.695167,0.227612,0.541045,0.304833,0.066914,0.194757,0.093633,...,0.227612,0.349624,0.522388,0.156716,0.735075,0.347015,0.543071,0.015038,0.274436,0.796226
2018 111,0.156425,0.235955,0.224719,0.561798,0.195531,0.430168,0.172222,0.055556,0.116667,0.055556,...,0.162921,0.452514,0.429379,0.135593,0.577778,0.166667,0.316667,0.033520,0.201117,0.664804
2018 112,0.230530,0.313480,0.233645,0.671875,0.236760,0.523364,0.243750,0.075000,0.213166,0.109718,...,0.127796,0.342949,0.532258,0.183871,0.730769,0.256410,0.529032,0.025974,0.266234,0.847403
2019 111,0.103286,0.241706,0.154930,0.502347,0.179245,0.429245,0.145540,0.051643,0.136150,0.056338,...,0.084906,0.252381,0.473934,0.127962,0.594340,0.165094,0.304348,0.004808,0.153846,0.657005
2019 112,0.260317,0.288889,0.151899,0.658228,0.178344,0.656051,0.278481,NaN,0.237342,0.094937,...,0.123418,0.376582,0.512658,0.183544,0.791139,0.265823,0.476190,0.028754,0.230032,0.816720
mean,0.187520,0.255592,0.183525,0.638939,0.192778,0.531156,0.218792,0.064068,0.164382,0.079016,...,0.143313,0.363514,0.494271,0.148636,0.684246,0.243837,0.446040,0.023933,0.226040,0.771804

In [6]:
def calculate_scores_post(df):
    df_result = pd.DataFrame()
    df_result["POST Q1"] = (df["POST Q1"].value_counts())
    df_result["POST Q2"] = (df["POST Q2"].value_counts())
    df_result["POST Q3"] = (df["POST Q3"].value_counts())
    df_result["POST Q4"] = (df["POST Q4"].value_counts())
    df_result["POST Q5"] = (df["POST Q5"].value_counts())
    df_result["POST Q6"] = (df["POST Q6"].value_counts())
    df_result["POST Q7"] = (df["POST Q7"].value_counts())
    df_result["POST Q8"] = (df["POST Q8"].value_counts())
    df_result["POST Q9"] = (df["POST Q9"].value_counts())
    df_result["POST Q10"] = (df["POST Q10"].value_counts())
    df_result["POST Q11"] = (df["POST Q11"].value_counts())
    df_result["POST Q12"] = (df["POST Q12"].value_counts())
    df_result["POST Q13"] = (df["POST Q13"].value_counts())
    df_result["POST Q14"] = (df["POST Q14"].value_counts())
    df_result["POST Q15"] = (df["POST Q15"].value_counts())
    df_result["POST Q16"] = (df["POST Q16"].value_counts())
    df_result["POST Q17"] = (df["POST Q17"].value_counts())
    df_result["POST Q18"] = (df["POST Q18"].value_counts())
    df_result["POST Q19"] = (df["POST Q19"].value_counts())
    df_result["POST Q20"] = (df["POST Q20"].value_counts())
    df_result["POST Q21"] = (df["POST Q21"].value_counts())
    df_result["POST Q22"] = (df["POST Q22"].value_counts())
    df_result["POST Q23"] = (df["POST Q23"].value_counts())
    df_result["POST Q24"] = (df["POST Q24"].value_counts())
    df_result["POST Q25"] = (df["POST Q25"].value_counts())
    df_result["POST Q26"] = (df["POST Q26"].value_counts())
    df_result["POST Q27"] = (df["POST Q27"].value_counts())
    df_result["POST Q28"] = (df["POST Q28"].value_counts())
    df_result["POST Q29"] = (df["POST Q29"].value_counts())
    df_result["POST Q30"] = (df["POST Q30"].value_counts())

    return df_result

In [7]:
def calculate_misconceptions_post(df):
    df_results = [0] * 32
    df_results[0] = (df["POST Q1"].D + df["POST Q1"].E)/df["POST Q1"].sum()
    df_results[1] = (df["POST Q2"].B + df["POST Q2"].C)/df["POST Q2"].sum()
    df_results[2] = (df["POST Q3"].A)/df["POST Q3"].sum()
    df_results[3] = (df["POST Q4"].A)/df["POST Q4"].sum()
    df_results[4] = (df["POST Q5"].E)/df["POST Q5"].sum()
    df_results[5] = (df["POST Q5"].C+df["POST Q5"].D+df["POST Q5"].E)/df["POST Q5"].sum()
    df_results[6] = (df["POST Q6"].A)/df["POST Q6"].sum()
    df_results[7] = (df["POST Q6"].C+df["POST Q6"].D+df["POST Q6"].E)/df["POST Q6"].sum()
    df_results[8] = (df["POST Q7"].A)/df["POST Q7"].sum()
    df_results[9] = (df["POST Q7"].E)/df["POST Q7"].sum()
    df_results[10] = (df["POST Q8"].A)/df["POST Q8"].sum()
    df_results[11] = (df["POST Q9"].C)/df["POST Q9"].sum()
    df_results[12] = (df["POST Q9"].D)/df["POST Q9"].sum()
    df_results[13] = (df["POST Q10"].B + df["POST Q10"].C)/df["POST Q10"].sum()
    df_results[14] = (df["POST Q11"].B + df["POST Q11"].C)/df["POST Q11"].sum()
    df_results[15] = (df["POST Q13"].A+df["POST Q13"].B+df["POST Q13"].C)/df["POST Q13"].sum()
    df_results[16] = (df["POST Q13"].E)/df["POST Q13"].sum()
    df_results[17] = (df["POST Q14"].E)/df["POST Q14"].sum()
    df_results[18] = (df["POST Q15"].B)/df["POST Q15"].sum()
    df_results[19] = (df["POST Q16"].B)/df["POST Q16"].sum()
    df_results[20] = (df["POST Q17"].A)/df["POST Q17"].sum()
    df_results[21] = (df["POST Q18"].C+df["POST Q18"].D+df["POST Q18"].E)/df["POST Q18"].sum()
    df_results[22] = (df["POST Q19"].A)/df["POST Q19"].sum()
    df_results[23] = (df["POST Q20"].A+df["POST Q20"].C)/df["POST Q20"].sum()
    df_results[24] = (df["POST Q25"].D)/df["POST Q25"].sum()
    df_results[25] = (df["POST Q25"].E)/df["POST Q25"].sum()
    df_results[26] = (df["POST Q26"].A+df["POST Q26"].B)/df["POST Q26"].sum()
    df_results[27] = (df["POST Q27"].A)/df["POST Q27"].sum()
    df_results[28] = (df["POST Q28"].D)/df["POST Q28"].sum()
    df_results[29] = (df["POST Q29"].E)/df["POST Q29"].sum()
    df_results[30] = (df["POST Q29"].C+df["POST Q29"].D)/df["POST Q29"].sum()
    df_results[31] = (df["POST Q30"].B+df["POST Q30"].D+df["POST Q30"].E)/df["POST Q30"].sum()
    
    return df_results

In [8]:
column_names=["POST Q1", "POST Q2", "POST Q3", "POST Q4", "POST Q5 32", "POST Q5 22",
             "POST Q6 31", "POST Q6 19", "POST Q7 31", "POST Q7 19", "POST Q8",
             "POST Q9 66", "POST Q9 9", "POST Q10 21", "POST Q11", "POST Q13 77 22",
             "POST Q13 69", "POST Q14", "POST Q15", "POST Q16", "POST Q17", "POST Q18", 
             "POST Q19", "POST 20", "POST Q25 76", "POST Q25 24", "POST Q26", "POST Q27",
             "POST Q28", "POST Q29 28", "POST Q29 air", "POST Q30"]
df2 = pd.DataFrame(columns=column_names)

df2.loc["2014 111"] = calculate_misconceptions_post(calculate_scores_post(df14_111))
df2.loc["2014 112"] = calculate_misconceptions_post(calculate_scores_post(df14_112))
df2.loc["2015 111"] = calculate_misconceptions_post(calculate_scores_post(df15_111))
df2.loc["2015 112"] = calculate_misconceptions_post(calculate_scores_post(df15_112))
df2.loc["2016 111"] = calculate_misconceptions_post(calculate_scores_post(df16_111))
df2.loc["2016 112"] = calculate_misconceptions_post(calculate_scores_post(df16_112))
df2.loc["2017 111"] = calculate_misconceptions_post(calculate_scores_post(df17_111))
df2.loc["2017 112"] = calculate_misconceptions_post(calculate_scores_post(df17_112))
df2.loc["2018 111"] = calculate_misconceptions_post(calculate_scores_post(df18_111))
df2.loc["2018 112"] = calculate_misconceptions_post(calculate_scores_post(df18_112))
df2.loc["2019 111"] = calculate_misconceptions_post(calculate_scores_post(df19_111))
df2.loc["2019 112"] = calculate_misconceptions_post(calculate_scores_post(df19_112))
df2.loc["mean"] = df2.mean()
df2.loc['std'] = df2.std()
df2.to_excel("misconception_by_question_POST.xlsx")
df2

,POST Q1,POST Q2,POST Q3,POST Q4,POST Q5 32,POST Q5 22,POST Q6 31,POST Q6 19,POST Q7 31,POST Q7 19,...,POST Q19,POST 20,POST Q25 76,POST Q25 24,POST Q26,POST Q27,POST Q28,POST Q29 28,POST Q29 air,POST Q30
2014 111,0.099338,0.251656,0.264901,0.258278,0.066225,0.496689,0.092715,0.039735,0.105960,0.026490,...,0.073333,0.306667,0.353333,0.100000,0.426667,0.166667,0.214765,0.020270,0.148649,0.500000
2014 112,0.161616,0.409091,0.287879,0.570707,0.252525,0.792929,0.121212,0.045455,0.106061,0.090909,...,0.121827,0.497462,0.532995,0.096447,0.705584,0.319797,0.441624,0.010152,0.233503,0.758974
2015 111,0.116402,0.255319,0.280423,0.380952,0.116402,0.507937,0.126984,0.111111,0.116402,0.047619,...,0.100529,0.333333,0.412698,0.063492,0.502646,0.227513,0.283422,0.021277,0.175532,0.524064
2015 112,0.098361,0.383673,0.254098,0.409836,0.106557,0.561475,0.127049,0.061475,0.106557,0.098361,...,0.102881,0.360656,0.495833,0.116667,0.655738,0.259259,0.362140,0.037344,0.219917,0.739496
2016 111,0.105882,0.294118,0.231373,0.363636,0.149606,0.539370,0.149606,0.051181,0.114173,0.023622,...,0.101215,0.306122,0.401639,0.094262,0.532787,0.196721,0.278008,0.008299,0.195021,0.535270
2016 112,0.160448,0.309701,0.134831,0.291045,0.111940,0.518657,0.104478,0.070896,0.160448,0.097015,...,0.134831,0.343284,0.436090,0.097744,0.705660,0.279245,0.248120,0.033835,0.142857,0.612782
2017 111,0.148148,0.287234,0.226316,0.273684,0.094737,0.510526,0.173684,NaN,0.131579,0.057895,...,0.074074,0.280423,0.344086,0.048387,0.449198,0.181818,0.203209,0.005319,0.132979,0.486631
2017 112,0.179487,0.368613,0.532847,0.175182,0.102564,0.479853,0.120879,0.047619,0.120438,0.062044,...,0.156934,0.215328,0.432234,0.065934,0.510949,0.248175,0.168498,0.007353,0.102941,0.592593
2018 111,0.158824,0.251497,0.405882,0.535294,0.152941,0.617647,0.152941,NaN,0.147059,0.047059,...,0.112426,0.323529,0.416667,0.130952,0.583333,0.178571,0.309524,0.005988,0.257485,0.652695
2018 112,0.197880,0.392857,0.607774,0.148410,0.123675,0.678445,0.084806,0.031802,0.123675,0.060071,...,0.081851,0.295374,0.440860,0.089606,0.521583,0.320144,0.190647,0.021505,0.125448,0.693141
2019 111,0.114286,0.233333,0.423810,0.200000,0.061905,0.404762,0.057143,NaN,0.076555,0.052632,...,0.043269,0.240385,0.268293,0.078049,0.403846,0.173077,0.188406,0.019324,0.144928,0.502415
2019 112,0.189024,0.327217,0.506098,0.149390,0.109756,0.594512,0.085366,0.021341,0.094512,0.073171,...,0.094512,0.253823,0.452599,0.116208,0.554878,0.289634,0.177370,0.006135,0.098160,0.633846
mean,0.144141,0.313693,0.346353,0.313035,0.120736,0.558567,0.116405,0.053402,0.116952,0.061407,...,0.099807,0.313032,0.415611,0.091479,0.546072,0.236719,0.255478,0.016400,0.164785,0.602659
std,0.034378,0.059263,0.139483,0.136330,0.047526,0.097724,0.031838,0.024685,0.021526,0.023764,...,0.028949,0.069230,0.066969,0.023139,0.096683,0.054884,0.080129,0.010564,0.049449,0.091193